export const mockTransactions = [
  {
    id: "37424-242356-99100",
    bill_address1: "123 Elm St",
    bill_address2: "Apt 4B",
    bill_address_id: 101,
    bill_city: "Springfield",
    bill_contact_email: "john.doe@example.com",
    bill_contact_first_name: "John",
    bill_contact_id: 201,
    bill_contact_last_name: "Doe",
    bill_contact_phone: "555-1234",
    bill_country: "USA",
    bill_customer_account: "AC12345",
    bill_customer_id: 301,
    bill_customer_name: "Acme Corp",
    bill_postal_code: "62701",
    bill_state: "IL",
    created_by: 1,
    creation_date: "2024-07-01",
    duration: "12 months",
    end_date: "2025-07-01",
    error_message: "",
    last_update_date: "2024-07-05",
    last_updated_by: 2,
    license_key: "XYZ123456789",
    notification_date: "2024-07-02",
    ocs_part_id: 401,
    organization_code: "ORG001",
    osc_part_number: "PART123",
    quantity: 10,
    reference_code: "REF001",
    reference_product: "Product A",
    ship_address1: "456 Oak St",
    ship_address2: "",
    ship_address_id: 102,
    ship_city: "Springfield",
    ship_contact_email: "jane.doe@example.com",
    ship_contact_first_name: "Jane",
    ship_contact_id: 202,
    ship_contact_last_name: "Doe",
    ship_contact_phone: "555-5678",
    ship_country: "USA",
    ship_customer_account: "AC67890",
    ship_customer_id: 302,
    ship_customer_name: "Beta LLC",
    ship_postal_code: "62702",
    ship_state: "IL",
    source_reference_date: "2024-06-30",
    source_reference_id: 501,
    source_reference_number: "SRC001",
    start_date: "2024-07-01",
    transaction_action: "new",
    transaction_date: "2024-07-01",
    transaction_number: 1001,
    transaction_source: "web",
    transaction_status: "completed",
    transaction_type: "sales",
    vendor_name: "Vendor X",
    vendor_part_number: "VEND123",
  },
  {
    id: "37424-242356-99101",
    bill_address1: "789 Pine St",
    bill_address2: "Suite 12",
    bill_address_id: 103,
    bill_city: "Shelbyville",
    bill_contact_email: "alice.smith@example.com",
    bill_contact_first_name: "Alice",
    bill_contact_id: 203,
    bill_contact_last_name: "Smith",
    bill_contact_phone: "555-8765",
    bill_country: "USA",
    bill_customer_account: "AC54321",
    bill_customer_id: 303,
    bill_customer_name: "Gamma Inc",
    bill_postal_code: "62565",
    bill_state: "IL",
    created_by: 3,
    creation_date: "2024-07-10",
    duration: "6 months",
    end_date: "2025-01-10",
    error_message: "Invalid data",
    last_update_date: "2024-07-12",
    last_updated_by: 4,
    license_key: "ABC987654321",
    notification_date: "2024-07-11",
    ocs_part_id: 402,
    organization_code: "ORG002",
    osc_part_number: "PART456",
    quantity: 5,
    reference_code: "REF002",
    reference_product: "Product B",
    ship_address1: "321 Maple St",
    ship_address2: "Floor 3",
    ship_address_id: 104,
    ship_city: "Shelbyville",
    ship_contact_email: "bob.jones@example.com",
    ship_contact_first_name: "Bob",
    ship_contact_id: 204,
    ship_contact_last_name: "Jones",
    ship_contact_phone: "555-4321",
    ship_country: "USA",
    ship_customer_account: "AC98765",
    ship_customer_id: 304,
    ship_customer_name: "Delta Ltd",
    ship_postal_code: "62566",
    ship_state: "IL",
    source_reference_date: "2024-07-09",
    source_reference_id: 502,
    source_reference_number: "SRC002",
    start_date: "2024-07-10",
    transaction_action: "update",
    transaction_date: "2024-07-10",
    transaction_number: 1002,
    transaction_source: "email",
    transaction_status: "pending",
    transaction_type: "rental",
    vendor_name: "Vendor Y",
    vendor_part_number: "VEND456",
  },
  {
    id: "37424-242356-99102",
    bill_address1: "654 Birch St",
    bill_address2: "Building A",
    bill_address_id: 105,
    bill_city: "Capital City",
    bill_contact_email: "charlie.brown@example.com",
    bill_contact_first_name: "Charlie",
    bill_contact_id: 205,
    bill_contact_last_name: "Brown",
    bill_contact_phone: "555-6789",
    bill_country: "USA",
    bill_customer_account: "AC67890",
    bill_customer_id: 305,
    bill_customer_name: "Epsilon Co",
    bill_postal_code: "62703",
    bill_state: "IL",
    created_by: 5,
    creation_date: "2024-07-15",
    duration: "3 months",
    end_date: "2024-10-15",
    error_message: "",
    last_update_date: "2024-07-16",
    last_updated_by: 6,
    license_key: "DEF456789012",
    notification_date: "2024-07-16",
    ocs_part_id: 403,
    organization_code: "ORG003",
    osc_part_number: "PART789",
    quantity: 20,
    reference_code: "REF003",
    reference_product: "Product C",
    ship_address1: "987 Cedar St",
    ship_address2: "Unit 5",
    ship_address_id: 106,
    ship_city: "Capital City",
    ship_contact_email: "david.wilson@example.com",
    ship_contact_first_name: "David",
    ship_contact_id: 206,
    ship_contact_last_name: "Wilson",
    ship_contact_phone: "555-7890",
    ship_country: "USA",
    ship_customer_account: "AC11223",
    ship_customer_id: 306,
    ship_customer_name: "Zeta Enterprises",
    ship_postal_code: "62704",
    ship_state: "IL",
    source_reference_date: "2024-07-14",
    source_reference_id: 503,
    source_reference_number: "SRC003",
    start_date: "2024-07-15",
    transaction_action: "renewal",
    transaction_date: "2024-07-15",
    transaction_number: 1003,
    transaction_source: "phone",
    transaction_status: "in-progress",
    transaction_type: "subscription",
    vendor_name: "Vendor Z",
    vendor_part_number: "VEND789",
  },
  {
    id: "37424-242356-99103",
    bill_address1: "234 Walnut St",
    bill_address2: "Suite 3A",
    bill_address_id: 108,
    bill_city: "Gotham",
    bill_contact_email: "frank.miller@example.com",
    bill_contact_first_name: "Frank",
    bill_contact_id: 208,
    bill_contact_last_name: "Miller",
    bill_contact_phone: "555-2345",
    bill_country: "USA",
    bill_customer_account: "AC34567",
    bill_customer_id: 308,
    bill_customer_name: "Iota Systems",
    bill_postal_code: "62901",
    bill_state: "IL",
    created_by: 9,
    creation_date: "2024-07-25",
    duration: "18 months",
    end_date: "2026-01-25",
    error_message: "",
    last_update_date: "2024-07-26",
    last_updated_by: 10,
    license_key: "JKL678901234",
    notification_date: "2024-07-26",
    ocs_part_id: 405,
    organization_code: "ORG005",
    osc_part_number: "PART345",
    quantity: 25,
    reference_code: "REF005",
    reference_product: "Product D",
    ship_address1: "654 Birch St",
    ship_address2: "",
    ship_address_id: 109,
    ship_city: "Gotham",
    ship_contact_email: "lucas.green@example.com",
    ship_contact_first_name: "Lucas",
    ship_contact_id: 209,
    ship_contact_last_name: "Green",
    ship_contact_phone: "555-4567",
    ship_country: "USA",
    ship_customer_account: "AC78901",
    ship_customer_id: 309,
    ship_customer_name: "Kappa Ltd",
    ship_postal_code: "62902",
    ship_state: "IL",
    source_reference_date: "2024-07-24",
    source_reference_id: 504,
    source_reference_number: "SRC004",
    start_date: "2024-07-25",
    transaction_action: "revoke",
    transaction_date: "2024-07-25",
    transaction_number: 1004,
    transaction_source: "fax",
    transaction_status: "canceled",
    transaction_type: "eval",
    vendor_name: "Vendor A",
    vendor_part_number: "VEND012",
  },
  {
    id: "37424-242356-99104",
    bill_address1: "987 Birchwood Dr",
    bill_address2: "Apt 9C",
    bill_address_id: 110,
    bill_city: "Star City",
    bill_contact_email: "hannah.lee@example.com",
    bill_contact_first_name: "Hannah",
    bill_contact_id: 210,
    bill_contact_last_name: "Lee",
    bill_contact_phone: "555-5678",
    bill_country: "USA",
    bill_customer_account: "AC45678",
    bill_customer_id: 310,
    bill_customer_name: "Lambda LLC",
    bill_postal_code: "63001",
    bill_state: "IL",
    created_by: 11,
    creation_date: "2024-07-30",
    duration: "2 years",
    end_date: "2026-07-30",
    error_message: "Shipping issue",
    last_update_date: "2024-07-31",
    last_updated_by: 12,
    license_key: "MNO789012345",
    notification_date: "2024-07-31",
    ocs_part_id: 406,
    organization_code: "ORG006",
    osc_part_number: "PART678",
    quantity: 30,
    reference_code: "REF006",
    reference_product: "Product E",
    ship_address1: "321 Oakwood Dr",
    ship_address2: "Suite 12B",
    ship_address_id: 111,
    ship_city: "Star City",
    ship_contact_email: "olivia.taylor@example.com",
    ship_contact_first_name: "Olivia",
    ship_contact_id: 211,
    ship_contact_last_name: "Taylor",
    ship_contact_phone: "555-6789",
    ship_country: "USA",
    ship_customer_account: "AC89012",
    ship_customer_id: 311,
    ship_customer_name: "Mu Enterprises",
    ship_postal_code: "63002",
    ship_state: "IL",
    source_reference_date: "2024-07-29",
    source_reference_id: 505,
    source_reference_number: "SRC005",
    start_date: "2024-07-30",
    transaction_action: "update",
    transaction_date: "2024-07-30",
    transaction_number: 1005,
    transaction_source: "web",
    transaction_status: "in-progress",
    transaction_type: "subscription",
    vendor_name: "Vendor B",
    vendor_part_number: "VEND345",
  },
  {
    id: "37424-242356-99105",
    bill_address1: "567 Elmwood Ave",
    bill_address2: "",
    bill_address_id: 112,
    bill_city: "Riverdale",
    bill_contact_email: "george.martin@example.com",
    bill_contact_first_name: "George",
    bill_contact_id: 212,
    bill_contact_last_name: "Martin",
    bill_contact_phone: "555-7890",
    bill_country: "USA",
    bill_customer_account: "AC56789",
    bill_customer_id: 312,
    bill_customer_name: "Nu Solutions",
    bill_postal_code: "63101",
    bill_state: "IL",
    created_by: 13,
    creation_date: "2024-08-01",
    duration: "9 months",
    end_date: "2025-05-01",
    error_message: "",
    last_update_date: "2024-08-02",
    last_updated_by: 14,
    license_key: "PQR890123456",
    notification_date: "2024-08-02",
    ocs_part_id: 407,
    organization_code: "ORG007",
    osc_part_number: "PART901",
    quantity: 12,
    reference_code: "REF007",
    reference_product: "Product F",
    ship_address1: "234 Maplewood Ln",
    ship_address2: "Unit 7",
    ship_address_id: 113,
    ship_city: "Riverdale",
    ship_contact_email: "mia.williams@example.com",
    ship_contact_first_name: "Mia",
    ship_contact_id: 213,
    ship_contact_last_name: "Williams",
    ship_contact_phone: "555-8901",
    ship_country: "USA",
    ship_customer_account: "AC34567",
    ship_customer_id: 313,
    ship_customer_name: "Xi Group",
    ship_postal_code: "63102",
    ship_state: "IL",
    source_reference_date: "2024-07-31",
    source_reference_id: 506,
    source_reference_number: "SRC006",
    start_date: "2024-08-01",
    transaction_action: "new",
    transaction_date: "2024-08-01",
    transaction_number: 1006,
    transaction_source: "phone",
    transaction_status: "completed",
    transaction_type: "sales",
    vendor_name: "Vendor C",
    vendor_part_number: "VEND678",
  },
  {
    id: "37424-242356-99106",
    bill_address1: "345 Ash St",
    bill_address2: "Floor 2",
    bill_address_id: 114,
    bill_city: "Smallville",
    bill_contact_email: "susan.jones@example.com",
    bill_contact_first_name: "Susan",
    bill_contact_id: 214,
    bill_contact_last_name: "Jones",
    bill_contact_phone: "555-3456",
    bill_country: "USA",
    bill_customer_account: "AC67890",
    bill_customer_id: 314,
    bill_customer_name: "Omega Ltd",
    bill_postal_code: "63201",
    bill_state: "IL",
    created_by: 15,
    creation_date: "2024-08-05",
    duration: "8 months",
    end_date: "2025-04-05",
    error_message: "",
    last_update_date: "2024-08-06",
    last_updated_by: 16,
    license_key: "STU123456789",
    notification_date: "2024-08-06",
    ocs_part_id: 408,
    organization_code: "ORG008",
    osc_part_number: "PART234",
    quantity: 8,
    reference_code: "REF008",
    reference_product: "Product G",
    ship_address1: "678 Cedar Ave",
    ship_address2: "",
    ship_address_id: 115,
    ship_city: "Smallville",
    ship_contact_email: "robert.doe@example.com",
    ship_contact_first_name: "Robert",
    ship_contact_id: 215,
    ship_contact_last_name: "Doe",
    ship_contact_phone: "555-4567",
    ship_country: "USA",
    ship_customer_account: "AC78901",
    ship_customer_id: 315,
    ship_customer_name: "Pi Group",
    ship_postal_code: "63202",
    ship_state: "IL",
    source_reference_date: "2024-08-04",
    source_reference_id: 507,
    source_reference_number: "SRC007",
    start_date: "2024-08-05",
    transaction_action: "update",
    transaction_date: "2024-08-05",
    transaction_number: 1007,
    transaction_source: "email",
    transaction_status: "completed",
    transaction_type: "sales",
    vendor_name: "Vendor D",
    vendor_part_number: "VEND901",
  },
  {
    id: "37424-242356-99107",
    bill_address1: "789 Oak St",
    bill_address2: "Suite 6B",
    bill_address_id: 116,
    bill_city: "Metropolis",
    bill_contact_email: "linda.martin@example.com",
    bill_contact_first_name: "Linda",
    bill_contact_id: 216,
    bill_contact_last_name: "Martin",
    bill_contact_phone: "555-5678",
    bill_country: "USA",
    bill_customer_account: "AC89012",
    bill_customer_id: 316,
    bill_customer_name: "Rho Inc",
    bill_postal_code: "63301",
    bill_state: "IL",
    created_by: 17,
    creation_date: "2024-08-10",
    duration: "5 months",
    end_date: "2025-01-10",
    error_message: "Payment issue",
    last_update_date: "2024-08-11",
    last_updated_by: 18,
    license_key: "VWX345678901",
    notification_date: "2024-08-11",
    ocs_part_id: 409,
    organization_code: "ORG009",
    osc_part_number: "PART567",
    quantity: 6,
    reference_code: "REF009",
    reference_product: "Product H",
    ship_address1: "123 Maple St",
    ship_address2: "Apt 10A",
    ship_address_id: 117,
    ship_city: "Metropolis",
    ship_contact_email: "james.smith@example.com",
    ship_contact_first_name: "James",
    ship_contact_id: 217,
    ship_contact_last_name: "Smith",
    ship_contact_phone: "555-6789",
    ship_country: "USA",
    ship_customer_account: "AC90123",
    ship_customer_id: 317,
    ship_customer_name: "Sigma Corp",
    ship_postal_code: "63302",
    ship_state: "IL",
    source_reference_date: "2024-08-09",
    source_reference_id: 508,
    source_reference_number: "SRC008",
    start_date: "2024-08-10",
    transaction_action: "renewal",
    transaction_date: "2024-08-10",
    transaction_number: 1008,
    transaction_source: "web",
    transaction_status: "completed",
    transaction_type: "subscription",
    vendor_name: "Vendor E",
    vendor_part_number: "VEND234",
  },
  {
    id: "37424-242356-99108",
    bill_address1: "123 Maplewood Ave",
    bill_address2: "Suite 9",
    bill_address_id: 118,
    bill_city: "Sunset Valley",
    bill_contact_email: "nancy.white@example.com",
    bill_contact_first_name: "Nancy",
    bill_contact_id: 218,
    bill_contact_last_name: "White",
    bill_contact_phone: "555-7890",
    bill_country: "USA",
    bill_customer_account: "AC01234",
    bill_customer_id: 318,
    bill_customer_name: "Tau Solutions",
    bill_postal_code: "63401",
    bill_state: "IL",
    created_by: 19,
    creation_date: "2024-08-15",
    duration: "7 months",
    end_date: "2025-03-15",
    error_message: "",
    last_update_date: "2024-08-16",
    last_updated_by: 20,
    license_key: "YZA456789012",
    notification_date: "2024-08-16",
    ocs_part_id: 410,
    organization_code: "ORG010",
    osc_part_number: "PART890",
    quantity: 18,
    reference_code: "REF010",
    reference_product: "Product I",
    ship_address1: "456 Pinewood Ln",
    ship_address2: "",
    ship_address_id: 119,
    ship_city: "Sunset Valley",
    ship_contact_email: "peter.johnson@example.com",
    ship_contact_first_name: "Peter",
    ship_contact_id: 219,
    ship_contact_last_name: "Johnson",
    ship_contact_phone: "555-8901",
    ship_country: "USA",
    ship_customer_account: "AC12345",
    ship_customer_id: 319,
    ship_customer_name: "Upsilon LLC",
    ship_postal_code: "63402",
    ship_state: "IL",
    source_reference_date: "2024-08-14",
    source_reference_id: 509,
    source_reference_number: "SRC009",
    start_date: "2024-08-15",
    transaction_action: "revoke",
    transaction_date: "2024-08-15",
    transaction_number: 1009,
    transaction_source: "fax",
    transaction_status: "canceled",
    transaction_type: "eval",
    vendor_name: "Vendor F",
    vendor_part_number: "VEND567",
  },
  {
    id: "37424-242356-99109",
    bill_address1: "456 Pine St",
    bill_address2: "Apt 12D",
    bill_address_id: 120,
    bill_city: "Springfield",
    bill_contact_email: "emily.brown@example.com",
    bill_contact_first_name: "Emily",
    bill_contact_id: 220,
    bill_contact_last_name: "Brown",
    bill_contact_phone: "555-8902",
    bill_country: "USA",
    bill_customer_account: "AC23456",
    bill_customer_id: 320,
    bill_customer_name: "Zeta Systems",
    bill_postal_code: "63501",
    bill_state: "IL",
    created_by: 21,
    creation_date: "2024-08-20",
    duration: "6 months",
    end_date: "2025-02-20",
    error_message: "",
    last_update_date: "2024-08-21",
    last_updated_by: 22,
    license_key: "BCD567890123",
    notification_date: "2024-08-21",
    ocs_part_id: 411,
    organization_code: "ORG011",
    osc_part_number: "PART123",
    quantity: 10,
    reference_code: "REF011",
    reference_product: "Product J",
    ship_address1: "789 Elm St",
    ship_address2: "",
    ship_address_id: 121,
    ship_city: "Springfield",
    ship_contact_email: "david.clark@example.com",
    ship_contact_first_name: "David",
    ship_contact_id: 221,
    ship_contact_last_name: "Clark",
    ship_contact_phone: "555-9012",
    ship_country: "USA",
    ship_customer_account: "AC34567",
    ship_customer_id: 321,
    ship_customer_name: "Eta Corp",
    ship_postal_code: "63502",
    ship_state: "IL",
    source_reference_date: "2024-08-19",
    source_reference_id: 510,
    source_reference_number: "SRC010",
    start_date: "2024-08-20",
    transaction_action: "new",
    transaction_date: "2024-08-20",
    transaction_number: 1010,
    transaction_source: "phone",
    transaction_status: "in-progress",
    transaction_type: "rental",
    vendor_name: "Vendor G",
    vendor_part_number: "VEND890",
  },
];
