export const mockTransactions = [
  {
    bill_address1: "123 Main St",
    bill_customer_name: "John Doe Corp",
    creation_date: "2023-01-01",
    license_key: "LIC123456789",
    ocs_part_id: 10,
    organization_code: "ORG001",
    quantity: 1,
    reference_code: "REF123",
    ship_customer_name: "Jane Doe Corp",
    transaction_action: "new",
    transaction_date: "2023-01-01",
    transaction_number: 1001,
    transaction_status: "completed",
    transaction_type: "sales",
  },
  {
    bill_address1: "456 Elm St",
    bill_customer_name: "Smith Enterprises",
    creation_date: "2023-02-15",
    license_key: "LIC987654321",
    ocs_part_id: 15,
    organization_code: "ORG002",
    quantity: 2,
    reference_code: "REF456",
    ship_customer_name: "Smith Enterprises",
    transaction_action: "update",
    transaction_date: "2023-02-15",
    transaction_number: 1002,
    transaction_status: "pending",
    transaction_type: "purchase",
  },
  {
    bill_address1: "789 Oak Ave",
    bill_customer_name: "ABC Corporation",
    creation_date: "2023-03-20",
    license_key: "LIC543216789",
    ocs_part_id: 20,
    organization_code: "ORG003",
    quantity: 3,
    reference_code: "REF789",
    ship_customer_name: "XYZ Inc.",
    transaction_action: "cancel",
    transaction_date: "2023-03-20",
    transaction_number: 1003,
    transaction_status: "failed",
    transaction_type: "return",
  },
  {
    bill_address1: "321 Pine Blvd",
    bill_customer_name: "Tech Solutions Ltd",
    creation_date: "2023-04-25",
    license_key: "LIC246813579",
    ocs_part_id: 25,
    organization_code: "ORG004",
    quantity: 4,
    reference_code: "REFABC",
    ship_customer_name: "Software Innovations",
    transaction_action: "new",
    transaction_date: "2023-04-25",
    transaction_number: 1004,
    transaction_status: "completed",
    transaction_type: "sales",
  },
  {
    bill_address1: "987 Maple Ln",
    bill_customer_name: "Global Ventures",
    creation_date: "2023-05-30",
    license_key: "LIC135792468",
    ocs_part_id: 30,
    organization_code: "ORG005",
    quantity: 5,
    reference_code: "REFXYZ",
    ship_customer_name: "Global Ventures",
    transaction_action: "update",
    transaction_date: "2023-05-30",
    transaction_number: 1005,
    transaction_status: "pending",
    transaction_type: "purchase",
  },
  {
    bill_address1: "654 Cedar Rd",
    bill_customer_name: "Data Solutions Inc",
    creation_date: "2023-06-10",
    license_key: "LIC864209753",
    ocs_part_id: 35,
    organization_code: "ORG006",
    quantity: 6,
    reference_code: "REF123XYZ",
    ship_customer_name: "Data Solutions Inc",
    transaction_action: "cancel",
    transaction_date: "2023-06-10",
    transaction_number: 1006,
    transaction_status: "failed",
    transaction_type: "return",
  },
  {
    bill_address1: "234 Walnut Dr",
    bill_customer_name: "Innovative Tech Corp",
    creation_date: "2023-07-15",
    license_key: "LIC753198642",
    ocs_part_id: 40,
    organization_code: "ORG007",
    quantity: 7,
    reference_code: "REF456ABC",
    ship_customer_name: "Innovative Tech Corp",
    transaction_action: "new",
    transaction_date: "2023-07-15",
    transaction_number: 1007,
    transaction_status: "completed",
    transaction_type: "sales",
  },
  {
    bill_address1: "876 Pine Ave",
    bill_customer_name: "Tech Innovations LLC",
    creation_date: "2023-08-20",
    license_key: "LIC620394871",
    ocs_part_id: 45,
    organization_code: "ORG008",
    quantity: 8,
    reference_code: "REF789XYZ",
    ship_customer_name: "Data Solutions Inc",
    transaction_action: "update",
    transaction_date: "2023-08-20",
    transaction_number: 1008,
    transaction_status: "pending",
    transaction_type: "purchase",
  },
  {
    bill_address1: "543 Oak Ln",
    bill_customer_name: "XYZ Tech Solutions",
    creation_date: "2023-09-25",
    license_key: "LIC509283746",
    ocs_part_id: 50,
    organization_code: "ORG009",
    quantity: 9,
    reference_code: "REFABC123",
    ship_customer_name: "Tech Innovations LLC",
    transaction_action: "cancel",
    transaction_date: "2023-09-25",
    transaction_number: 1009,
    transaction_status: "failed",
    transaction_type: "return",
  },
  {
    bill_address1: "765 Maple Blvd",
    bill_customer_name: "ABC Software Inc",
    creation_date: "2023-10-30",
    license_key: "LIC735620194",
    ocs_part_id: 55,
    organization_code: "ORG010",
    quantity: 10,
    reference_code: "REFXYZ456",
    ship_customer_name: "Global Ventures",
    transaction_action: "new",
    transaction_date: "2023-10-30",
    transaction_number: 1010,
    transaction_status: "completed",
    transaction_type: "sales",
  },
];
