export const mockProducts = [
  {
    id: "37424-242356-13100",
    attribute1: "Value1A",
    attribute2: "Value2A",
    attribute3: "Value3A",
    attribute4: "Value4A",
    attribute5: "Value5A",
    created_by: 1,
    creation_date: "2024-01-15",
    duration: "30 days",
    enabled_flag: "Y",
    eval_set_name: "EvalSetA",
    last_update_date: "2024-01-20",
    last_updated_by: 2,
    license_source_set: "LicenseA",
    new_set_name: "NewSetA",
    organization_code: "ORG1",
    osc_product_id: 101,
    product_description: "Description of Product A",
    product_id: 1001,
    product_name: "ProductA",
    renewal_set_name: "RenewalSetA",
    source_name: "SourceA",
    vendor_name: "VendorA",
    vendor_part_number: "VP1001",
  },
  {
    id: "37424-242356-13101",
    attribute1: "Value1B",
    attribute2: "Value2B",
    attribute3: "Value3B",
    attribute4: "Value4B",
    attribute5: "Value5B",
    created_by: 2,
    creation_date: "2024-02-10",
    duration: "60 days",
    enabled_flag: "N",
    eval_set_name: "EvalSetB",
    last_update_date: "2024-02-15",
    last_updated_by: 3,
    license_source_set: "LicenseB",
    new_set_name: "NewSetB",
    organization_code: "ORG2",
    osc_product_id: 102,
    product_description: "Description of Product B",
    product_id: 1002,
    product_name: "ProductB",
    renewal_set_name: "RenewalSetB",
    source_name: "SourceB",
    vendor_name: "VendorB",
    vendor_part_number: "VP1002",
  },
  {
    id: "37424-242356-13102",
    attribute1: "Value1C",
    attribute2: "Value2C",
    attribute3: "Value3C",
    attribute4: "Value4C",
    attribute5: "Value5C",
    created_by: 3,
    creation_date: "2024-03-05",
    duration: "90 days",
    enabled_flag: "Y",
    eval_set_name: "EvalSetC",
    last_update_date: "2024-03-10",
    last_updated_by: 4,
    license_source_set: "LicenseC",
    new_set_name: "NewSetC",
    organization_code: "ORG3",
    osc_product_id: 103,
    product_description: "Description of Product C",
    product_id: 1003,
    product_name: "ProductC",
    renewal_set_name: "RenewalSetC",
    source_name: "SourceC",
    vendor_name: "VendorC",
    vendor_part_number: "VP1003",
  },
  {
    id: "37424-242356-13103",
    attribute1: "Value1D",
    attribute2: "Value2D",
    attribute3: "Value3D",
    attribute4: "Value4D",
    attribute5: "Value5D",
    created_by: 4,
    creation_date: "2024-04-01",
    duration: "120 days",
    enabled_flag: "Y",
    eval_set_name: "EvalSetD",
    last_update_date: "2024-04-05",
    last_updated_by: 5,
    license_source_set: "LicenseD",
    new_set_name: "NewSetD",
    organization_code: "ORG4",
    osc_product_id: 104,
    product_description: "Description of Product D",
    product_id: 1004,
    product_name: "ProductD",
    renewal_set_name: "RenewalSetD",
    source_name: "SourceD",
    vendor_name: "VendorD",
    vendor_part_number: "VP1004",
  },
  {
    id: "37424-242356-13104",
    attribute1: "Value1E",
    attribute2: "Value2E",
    attribute3: "Value3E",
    attribute4: "Value4E",
    attribute5: "Value5E",
    created_by: 5,
    creation_date: "2024-05-20",
    duration: "150 days",
    enabled_flag: "N",
    eval_set_name: "EvalSetE",
    last_update_date: "2024-05-25",
    last_updated_by: 6,
    license_source_set: "LicenseE",
    new_set_name: "NewSetE",
    organization_code: "ORG5",
    osc_product_id: 105,
    product_description: "Description of Product E",
    product_id: 1005,
    product_name: "ProductE",
    renewal_set_name: "RenewalSetE",
    source_name: "SourceE",
    vendor_name: "VendorE",
    vendor_part_number: "VP1005",
  },
  {
    id: "37424-242356-13105",
    attribute1: "Value1F",
    attribute2: "Value2F",
    attribute3: "Value3F",
    attribute4: "Value4F",
    attribute5: "Value5F",
    created_by: 6,
    creation_date: "2024-06-12",
    duration: "180 days",
    enabled_flag: "Y",
    eval_set_name: "EvalSetF",
    last_update_date: "2024-06-17",
    last_updated_by: 7,
    license_source_set: "LicenseF",
    new_set_name: "NewSetF",
    organization_code: "ORG6",
    osc_product_id: 106,
    product_description: "Description of Product F",
    product_id: 1006,
    product_name: "ProductF",
    renewal_set_name: "RenewalSetF",
    source_name: "SourceF",
    vendor_name: "VendorF",
    vendor_part_number: "VP1006",
  },
  {
    id: "37424-242356-13106",
    attribute1: "Value1G",
    attribute2: "Value2G",
    attribute3: "Value3G",
    attribute4: "Value4G",
    attribute5: "Value5G",
    created_by: 7,
    creation_date: "2024-07-01",
    duration: "210 days",
    enabled_flag: "N",
    eval_set_name: "EvalSetG",
    last_update_date: "2024-07-05",
    last_updated_by: 8,
    license_source_set: "LicenseG",
    new_set_name: "NewSetG",
    organization_code: "ORG7",
    osc_product_id: 107,
    product_description: "Description of Product G",
    product_id: 1007,
    product_name: "ProductG",
    renewal_set_name: "RenewalSetG",
    source_name: "SourceG",
    vendor_name: "VendorG",
    vendor_part_number: "VP1007",
  },
  {
    id: "37424-242356-13107",
    attribute1: "Value1H",
    attribute2: "Value2H",
    attribute3: "Value3H",
    attribute4: "Value4H",
    attribute5: "Value5H",
    created_by: 8,
    creation_date: "2024-08-15",
    duration: "240 days",
    enabled_flag: "Y",
    eval_set_name: "EvalSetH",
    last_update_date: "2024-08-20",
    last_updated_by: 9,
    license_source_set: "LicenseH",
    new_set_name: "NewSetH",
    organization_code: "ORG8",
    osc_product_id: 108,
    product_description: "Description of Product H",
    product_id: 1008,
    product_name: "ProductH",
    renewal_set_name: "RenewalSetH",
    source_name: "SourceH",
    vendor_name: "VendorH",
    vendor_part_number: "VP1008",
  },
  {
    id: "37424-242356-13108",
    attribute1: "Value1I",
    attribute2: "Value2I",
    attribute3: "Value3I",
    attribute4: "Value4I",
    attribute5: "Value5I",
    created_by: 9,
    creation_date: "2024-09-10",
    duration: "270 days",
    enabled_flag: "N",
    eval_set_name: "EvalSetI",
    last_update_date: "2024-09-15",
    last_updated_by: 10,
    license_source_set: "LicenseI",
    new_set_name: "NewSetI",
    organization_code: "ORG9",
    osc_product_id: 109,
    product_description: "Description of Product I",
    product_id: 1009,
    product_name: "ProductI",
    renewal_set_name: "RenewalSetI",
    source_name: "SourceI",
    vendor_name: "VendorI",
    vendor_part_number: "VP1009",
  },
  {
    id: "37424-242356-13109",
    attribute1: "Value1J",
    attribute2: "Value2J",
    attribute3: "Value3J",
    attribute4: "Value4J",
    attribute5: "Value5J",
    created_by: 10,
    creation_date: "2024-10-01",
    duration: "300 days",
    enabled_flag: "Y",
    eval_set_name: "EvalSetJ",
    last_update_date: "2024-10-05",
    last_updated_by: 11,
    license_source_set: "LicenseJ",
    new_set_name: "NewSetJ",
    organization_code: "ORG10",
    osc_product_id: 110,
    product_description: "Description of Product J",
    product_id: 1010,
    product_name: "ProductJ",
    renewal_set_name: "RenewalSetJ",
    source_name: "SourceJ",
    vendor_name: "VendorJ",
    vendor_part_number: "VP1010",
  },
  {
    id: "37424-242356-13110",
    attribute1: "Value1K",
    attribute2: "Value2K",
    attribute3: "Value3K",
    attribute4: "Value4K",
    attribute5: "Value5K",
    created_by: 11,
    creation_date: "2024-11-10",
    duration: "330 days",
    enabled_flag: "N",
    eval_set_name: "EvalSetK",
    last_update_date: "2024-11-15",
    last_updated_by: 12,
    license_source_set: "LicenseK",
    new_set_name: "NewSetK",
    organization_code: "ORG11",
    osc_product_id: 111,
    product_description: "Description of Product K",
    product_id: 1011,
    product_name: "ProductK",
    renewal_set_name: "RenewalSetK",
    source_name: "SourceK",
    vendor_name: "VendorK",
    vendor_part_number: "VP1011",
  },
  {
    id: "37424-242356-13111",
    attribute1: "Value1L",
    attribute2: "Value2L",
    attribute3: "Value3L",
    attribute4: "Value4L",
    attribute5: "Value5L",
    created_by: 12,
    creation_date: "2024-12-01",
    duration: "360 days",
    enabled_flag: "Y",
    eval_set_name: "EvalSetL",
    last_update_date: "2024-12-05",
    last_updated_by: 13,
    license_source_set: "LicenseL",
    new_set_name: "NewSetL",
    organization_code: "ORG12",
    osc_product_id: 112,
    product_description: "Description of Product L",
    product_id: 1012,
    product_name: "ProductL",
    renewal_set_name: "RenewalSetL",
    source_name: "SourceL",
    vendor_name: "VendorL",
    vendor_part_number: "VP1012",
  },
];
